//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.14 at 03:30:27 PM CST 
//


package com.saintdan.util.wechat.xmlObj;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.saintdan.util.wechat.xmlObj package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class XmlObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.saintdan.util.wechat.xmlObj
     * 
     */
    public XmlObjectFactory() {
    }

    /**
     * Create an instance of {@link ImgMsgXmlObj }
     * 
     */
    public ImgMsgXmlObj createImgMsgXmlObj() {
        return new ImgMsgXmlObj();
    }

    /**
     * Create an instance of {@link LinkMsgXmlObj }
     *
     */
    public LinkMsgXmlObj createLinkMsgXmlObj() {
        return new LinkMsgXmlObj();
    }

    /**
     * Create an instance of {@link LocationMsgXmlObj }
     *
     */
    public LocationMsgXmlObj createLocationMsgXmlObj() {
        return new LocationMsgXmlObj();
    }

    /**
     * Create an instance of {@link ShortVideoMsgXmlObj }
     *
     */
    public ShortVideoMsgXmlObj createShortVideoXmlObj() {
        return new ShortVideoMsgXmlObj();
    }

    /**
     * Create an instance of {@link TextMsgXmlObj }
     *
     */
    public TextMsgXmlObj createTextMsgXmlObj() {
        return new TextMsgXmlObj();
    }

    /**
     * Create an instance of {@link VideoMsgXmlObj }
     *
     */
    public VideoMsgXmlObj createVideoMsgXmlObj() {
        return new VideoMsgXmlObj();
    }

    /**
     * Create an instance of {@link VoiceMsgXmlObj }
     *
     */
    public VoiceMsgXmlObj createVoiceMsgXmlObj() {
        return new VoiceMsgXmlObj();
    }

}
